### ISSUE TITLE
error pada saat membuka beberapa situs web

### ISSUE THREAD

**Issue by AdrianHs87** [muhrizki1996/PiHole-AdBlocker-List#1]
ada beberapa url yang tidak seharusnya diblokir tetapi ada didalam list..

beberapa diantaranya : netdna.bootstrapcdn.com, pixel.wp.com, stats.wp.com

sehingga, pada saat membuka situs seperti http://wordpress.com/posts/xxx.home.blog atau web yang menggunakan css bootstrap online tidak dapat tampil dengan baik..

**Comment by muhrizki1996** [comment]
@AdrianHs87 terimakasih atas reportnya.. sebentar malam akan saya update file hosts nya..

-Muhammad Rizki-
